# Generated by Django 5.2.7 on 2025-12-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='timestamp',
            new_name='date_created',
        ),
    ]
